USER_EMAIL_HELPER = "The Email field must be set"
USER_PASSWORD_HELPER = "The Password field must be set"
FIRST_NAME_LIMIT = 30
LAST_NAME_LIMIT = 150
MAX_LENGTH_PROJECT_NAME = 100
MAX_LENGTH_TODO_NAME = 1000
